// Generated by Wrangler on Sun Jul 28 2024 18:44:42 GMT+0100 (British Summer Time)
// by running `wrangler types`

interface Env {
	airtableOAuthStore: KVNamespace;
	CLIENT_ID: string;
	CLIENT_SECRET: string;
	PLUGIN_URI: string;
	REDIRECT_URI: string;
	AUTHORIZE_ENDPOINT: string;
	TOKEN_ENDPOINT: string;
	SCOPE: string;
}
