#:schema node_modules/wrangler/config-schema.json
name = "framer-airtable-api"
main = "src/index.ts"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "airtableOAuthStore"
id = "503db01796e6450dafce3504c2c45e52"
